### ISSUE TITLE
[REG] Riya Vashisht

### ISSUE THREAD

**Issue by RiyaVashisht** [SICSR-ACM-Student-Chapter/50-Days-of-Euler#20]
**Name: Riya Vashisht** 

**Organization: SICSR** 

**Stream: BCA** 

**Discord Username: riyavash#9191**

**Comment by Amorpheuz** [comment]
Hey Riya, Great to have you participate! Have you joined the discord Server? If so, Can you check your discord username again? I can find a `Riya Vashisht#1959` on the server, would that be you?
